title: GNSSLIB Documentation
theme: jekyll-theme-minimal
markdown: kramdown

include:
  - _includes
defaults:
  - scope:
      path: ""
    values:
      layout: default
      head: _includes/head-custom.html
